name: Terraform Deployment to Prod

on:
<<<<<<< HEAD:.github/workflows/ci-action.yml
  push:
    #branches:
      #- main
  workflow_dispatch:
=======
  #  push:
  #    branches:
  #      - main
  workflow-dispatch:
>>>>>>> 7b8b2cdfa6794ef8e642601f1b3771710a14e511:.github/ci-action.yml
jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials configured"

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan
#      - name: Apply Terraform
#        if: github.ref == 'refs/heads/main'
#        run: terraform apply -auto-approve tfplan
#        env:
#          TF_VAR_environment: prod
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
